name: OHRI Namibia SSH

on:
  push:
    branches:
      - dev
      - demo
      - working 
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  namibia_dev_server_connection:
      runs-on: ubuntu-latest
      
      steps:      
        - name: SSH to remote OHRI Dev server 
          run: | 
            ssh -o StrictHostKeyChecking=no llemos@reports.globalhealthapp.net -p 3220 -v
            ls -la -t  && \
            cd /opt && \
            ls -la -t 
            
  namibia_working_server_connection:
        runs-on: ubuntu-latest

        steps:      
          - name: SSH to remote OHRI Dev server 
            run: | 
              ssh -o StrictHostKeyChecking=no llemos@reports.globalhealthapp.net -p 3221 -v
              ls -la -t  && \
              cd /opt && \
              ls -la -t 
      
  namibia_demo_server_connection:
        runs-on: ubuntu-latest

        steps:      
          - name: SSH to remote OHRI Dev server 
            run: | 
              ssh -o StrictHostKeyChecking=no llemos@reports.globalhealthapp.net -p 2202 -v
              ls -la -t  && \
              cd /opt && \
              ls -la -t 